twig:
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true

knp_paginator:
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'

